export const FETCH_CATEGORY_START = 'category/FETCH_CATEGORIES_START';
export const FETCH_CATEGORY_SUCCESS = 'category/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'category/FETCH_CATEGORIES_FAILED';
